.github/workflows/rust.yml
Automated testing for the validator daemon (soon to be renamed orchestrator)
=> Add Rust tests via github actions

module/x/peggy/alias.go, module/x/peggy/client/cli/tx.go, module/x/peggy/client/rest/tx.go, module/x/peggy/handler.go, module/x/peggy/keeper/querier_test.go, module/x/peggy/types/msgs.go, module/x/peggy/types/types.go, module/x/peggy/types/types_test.go, tests/container-scripts/run-eth.sh, tests/start-chains.sh, tests/test-runner/Cargo.toml, tests/test-runner/src/main.rs
I'm still not totally sure that the encoding here is correct, need to do some testing and catch minor runtime issues, also add tests in general.
=> Valset response verification

module/contrib/local/README.md, module/contrib/local/fake_deposit_attestation.sh, module/contrib/local/fake_multisig_attestation.sh, module/contrib/local/fake_withdraw_attestation.sh, module/contrib/local/setup_node.sh, module/contrib/local/start_node.sh, module/x/peggy/client/cli/oracle_tx.go, module/x/peggy/client/cli/query.go, module/x/peggy/client/cli/tx.go, module/x/peggy/client/rest/query.go, module/x/peggy/client/rest/rest.go, module/x/peggy/handler.go, module/x/peggy/keeper/attestation_handler.go, module/x/peggy/keeper/batch.go, module/x/peggy/keeper/batch_test.go, module/x/peggy/keeper/pool.go, module/x/peggy/keeper/pool_test.go, module/x/peggy/keeper/querier.go, module/x/peggy/types/batch.go, module/x/peggy/types/codec.go, module/x/peggy/types/errors.go, module/x/peggy/types/ethereum.go, module/x/peggy/types/key.go, module/x/peggy/types/msgs.go, module/x/peggy/types/oracle.go, module/x/peggy/types/pool.go, module/x/peggy/types/types.go
* New CLI commands and query handlers
* Dev scripts for manual tests
* Some code cleanup and documentation
=> Attestation workflow

.github/workflows/docker-image.yml, tests/all-up-test.sh, tests/container-scripts/all-up-test-internal.sh, tests/solidity-only.sh, tests/test-runner/src/main.rs
This adds the all up testing script to github actions
=> Add all up test

tests/container-scripts/run-testnet.sh
=> Enable debug logs for local testnet

design/overview.md
This resolves some of the questions in https://github.com/althea-net/peggy/issues/70
=> Orchestrator -> Eth Signer + Relayer, and clarification of batch logic

module/x/peggy/client/rest/query.go, module/x/peggy/client/rest/rest.go, module/x/peggy/keeper/querier.go
This tracks a PR to delete dead code, and do other cleanups
=> Cleanup part 1

tests/dockerfile/Dockerfile
This should net us a few minutes every integration test.
=> Use check instead of build in tests

.github/workflows/docker-image.yml, orchestrator/Cargo.lock, orchestrator/orchestrator/src/oracle_resync.rs, orchestrator/peggy_utils/Cargo.toml, orchestrator/peggy_utils/src/lib.rs, orchestrator/peggy_utils/src/types/ethereum_events.rs, orchestrator/peggy_utils/src/types/valsets.rs, orchestrator/relayer/src/batch_relaying.rs, orchestrator/relayer/src/valset_relaying.rs, orchestrator/test_runner/src/happy_path.rs, orchestrator/test_runner/src/main.rs, orchestrator/test_runner/src/valset_stress.rs, tests/all-up-test.sh, tests/container-scripts/all-up-test-internal.sh, tests/container-scripts/integration-tests.sh, tests/container-scripts/reload-code.sh, tests/run-tests.sh
This patch replaces the single flow integration test with mutliple
different integration test flows to be run in parallel in github
actions. The hope being that we can validate specific things in more
extreme ways while still maintaining a simple to understand happy path
test as the default.
=> WIP: Break out multiple integration tests

orchestrator/client/src/main.rs, orchestrator/orchestrator/src/oracle_resync.rs, orchestrator/test_runner/src/bootstrapping.rs, orchestrator/test_runner/src/main.rs, solidity/contract-deployer.ts, solidity/contracts/Peggy.sol, solidity/contracts/TestERC20A.sol, solidity/contracts/TestERC20B.sol, solidity/contracts/TestERC20C.sol, solidity/test-utils/index.ts
This expands the number of ERC20 tokens used in our testing environments
=> Use three erc20 tokens for testing

orchestrator/cosmos_peggy/src/send.rs, orchestrator/ethereum_peggy/src/send_to_cosmos.rs, orchestrator/orchestrator/Cargo.toml, orchestrator/orchestrator/src/main_loop.rs, orchestrator/orchestrator/src/oracle_resync.rs, orchestrator/peggy_utils/src/error.rs, orchestrator/peggy_utils/src/types/valsets.rs, orchestrator/relayer/src/find_latest_valset.rs, orchestrator/test_runner/src/happy_path.rs, orchestrator/test_runner/src/main.rs, orchestrator/test_runner/src/transaction_stress_test.rs, orchestrator/test_runner/src/utils.rs, orchestrator/test_runner/src/valset_stress.rs, solidity/contracts/TestERC20A.sol, solidity/contracts/TestERC20B.sol, solidity/contracts/TestERC20C.sol, tests/dockerfile/Dockerfile
This patch deploys three ERC20 contracts and I'm working on a way to
do thousands of token sends in the tests.
=> Transaction Stress Test

module/x/peggy/keeper/msg_server.go
Just a minor edge case I thought of but haven't taken the time to fix.
=> Add warning comment about potential storage spam

readme.md
We now have these features worked out, so we should mark that in the readme.md
=> Check more boxes

orchestrator/orchestrator/src/oracle_resync.rs
This new oracle resync function handles the corner case where an
orchestrator has crashed and needs to be restarted and during that time
has missed the first eventNonce on the Ethereum blockchain during that time.
Previously this case was ignored, if the validator had never submitted any
oracle claims before we simply assumed no events had ever happened. This
can't be ignored now becuase it may result in the slashing of an
unfortunate validator. Not to mention halt the first event from being
executed if it happens to enough validators at the same time.
The new code efficiently searches back to creation of the peggy contract
and confirms that all possible events have been submitted as oracle
messages to the Cosmos chain.
=> More efficient and correct nonce bootstrapping

orchestrator/test_runner/src/happy_path.rs
In order to generate validator sets for validator set update tests
we vary the validator set power randomly. For the validator out test
this isn't feasible because we use only 3 validators in our test
environment. Meaning even a 1% allocation to the down validator will
result in the remaining online validators not having enough power to
operate the bridge.
This is a good argument for using a 4 or 5 validator set in CI but we
are already resource constrained enough. So for now lets just disable
the validator set update testing part of the validator out flow and
replace it with a simple check that the validator set on Ethereum is
nonzero.
=> Fix validator out test

solidity/contracts/CosmosToken.sol, solidity/contracts/Peggy.sol, solidity/test/deployERC20.ts
This adds the `deployERC20` function to the contract which deploys an ERC20 whose entire balance is controlled by the Peggy.sol contract. It also tests it, as well as submitting a batch to transfer tokens out of it.
=> Peggyv2 Solidity

.github/workflows/automated-release.yml, module/x/peggy/keeper/attestation.go, orchestrator/client/src/main.rs, orchestrator/orchestrator/src/ethereum_event_watcher.rs, orchestrator/orchestrator/src/main_loop.rs, orchestrator/peggy_utils/src/types/valsets.rs, orchestrator/register_delegate_keys/src/main.rs, orchestrator/relayer/src/batch_relaying.rs, orchestrator/relayer/src/find_latest_valset.rs, orchestrator/relayer/src/valset_relaying.rs, orchestrator/test_runner/src/main.rs, solidity/contracts/TestERC20A.sol, solidity/contracts/TestERC20B.sol, solidity/contracts/TestERC20C.sol, solidity/scripts/contract-deployer.sh
Just various things I'm patching for the Althea testnet
=> Testnet fixes

module/x/peggy/cosmos-originated_test.go, module/x/peggy/handler.go, module/x/peggy/keeper/attestation.go, module/x/peggy/keeper/attestation_handler.go, module/x/peggy/keeper/batch.go, module/x/peggy/keeper/genesis.go, module/x/peggy/keeper/msg_server.go, module/x/peggy/keeper/pool.go, module/x/peggy/types/codec.go, module/x/peggy/types/ethereum.go, module/x/peggy/types/key.go, module/x/peggy/types/msgs.go
Just trying to rebase this instead of merge it and see if that helps with the tests.
=> v2 unit tests rebase

module/x/peggy/handler_test.go, module/x/peggy/keeper/batch.go, module/x/peggy/keeper/batch_test.go, module/x/peggy/types/ethereum.go, module/x/peggy/types/key.go, orchestrator/cosmos_peggy/src/messages.rs, orchestrator/test_runner/src/main.rs, orchestrator/test_runner/src/transaction_stress_test.rs
Just a few line line fix and a lot of tests.
=> Fix deposits of more than 18 ETH

module/x/peggy/types/codec.go, orchestrator/peggy_utils/src/types/ethereum_events.rs
This seems to register the ERC20 contract correctly. 
Next steps:
=> Gravity V2 End to End 

orchestrator/client/src/main.rs
This updates client error messages to better display the case where you
don't have enough funds.
=> Update client error messages

slashing-spec.md
The intention of this document is mostly to name the different slashing conditions at a high level so that we don't get confused while talking about them. Please feel free to edit these if necessary, and add slashing conditions that I have forgotten or that have become necessary.
=> Slashing spec

.github/workflows/integration-tests.yml, .github/workflows/rust.yml, orchestrator/Cargo.lock, orchestrator/gbt/Cargo.toml, orchestrator/test_runner/src/main.rs, tests/assets/ETHGenesis_london.json, tests/container-scripts/run-eth-london.sh, tests/container-scripts/run-testnet.sh, tests/dockerfile/Dockerfile, tests/run-all-tests.sh
Gorli has undergone a hardfork update for the Gorli testnet, therefore we should add it to our test cases.
This pr also does some test environment updates and expands rust test coverage.
=> London hardfork testing

orchestrator/test_runner/src/relay_market.rs
This test asserts that unprofitable batches will not be relayed. The test creates a batch with a reward of 1 wei's worth of CosmosDai (~2500 uDAI at the point the ethereum chain was pegged in Hardhat) and waits to make sure no active relayer attempts to relay it.
=> Adding relayer batch failure case test

orchestrator/ethereum_gravity/src/utils.rs, orchestrator/orchestrator/src/main_loop.rs, orchestrator/relayer/src/main_loop.rs
This is a very minor ergonomics issue that bothered me the last time I
looked at it.
=> GravityID should be returned as a string

module/x/gravity/keeper/batch.go, module/x/gravity/keeper/batch_test.go, module/x/gravity/keeper/cosmos-originated.go, module/x/gravity/keeper/pool.go, module/x/gravity/keeper/pool_test.go
Adding more tests related to the new tx pool indexing model, as well as performing some edge case analysis for the main public methods.
A few public methods would cause nil pointers rather than return errors, so added some checks to handle invalid arguments
=> Tx Pool tests + parameter checking

module/x/gravity/keeper/pool_test.go
=> Adding ExportGenesis test for pool txs

.github/workflows/rust.yml, orchestrator/Cargo.lock, orchestrator/Cargo.toml, orchestrator/test_runner/src/main.rs, solidity/contracts/Gravity.sol, tests/all-up-test.sh, tests/run-all-tests.sh
Just a series of minor typo and script fixes
=> Small fixes

module/x/gravity/abci.go, module/x/gravity/abci_test.go, module/x/gravity/keeper/batch.go, module/x/gravity/keeper/batch_test.go, module/x/gravity/keeper/evidence_test.go, module/x/gravity/keeper/genesis.go, module/x/gravity/keeper/grpc_query.go, module/x/gravity/keeper/querier.go, module/x/gravity/types/batch.go, module/x/gravity/types/batch_test.go
Adds InternalOutgoingTxBatch which duplicates OutgoingTxBatch with validated members
=> Consistent Eth Addresses - OutgoingTxBatch
