- module/x/peggy/client/rest/query.go
🚧   Draft for early feedback
Resolves #2 
The fix is quite trivial but automated tests are very complex as they require a running node. 
I was only able to manually verify that `curl http://localhost:1317/peggy/current_valset` returns the proper hight now.
Todo:
`getValsetConfirmHandler` was not modified, yet because it seems not to return anything.
> Add block height to rest responses

- design/overview.md
Starts work on #7 
Closes #12 
Addresses #5 (but probably needs more details for closing that)
I begin a detailed design spec and so far make some definitions and details on the bootstrapping phase. Once we get the high-level details on the sections specified, we should link to other documents explaining the detailed message types and the actual process the Orchestrator handles (ping REST, encode to RLP, sign and post, etc)
Much of this is pulled from diverse markdowns, issues, and conversations I have had. But I want one cannonical reference we can all use that is much larger than the issues and PRs.
> Begin Specification

- design/overview.md
This compares Validator Set, Orchestrator Set, and MultiSig Set.
And argues that if we regularly update the MultiSig Set on Ethereum (a mirror of the Validator Set), and we can trace any Orchestrator misbehavior to a message signed by one of their two keys, then the entire peg zone operation has the full security of the validator set, which is what IBC gives us.
> Define security levels of all keys

- module/x/peggy/client/rest/query.go
- module/x/peggy/client/rest/rest.go
- module/x/peggy/keeper/keeper.go
- module/x/peggy/keeper/keeper_test.go
- module/x/peggy/keeper/querier.go
- module/x/peggy/keeper/querier_test.go
- module/x/peggy/keeper/test_common.go
- module/x/peggy/types/codec.go
Resolves #3 
With this PR three new endpoints are added that can:
```sh
curl http://localhost:1317/peggy/pending_valset_requests/cosmos12flmaejjvzdtz58s4m5avx30wm8uffe7ycj4l9 -H "Content-Type: application/json"
```
Response: 
```json
{"height":"2790","result":{
"type": "peggy/Valset",
"value": {
"Nonce": "2162",
"Powers": [
"1000"
],
"EthAddresses": [
"0xb462864E395d88d6bc7C5dd5F3F5eb4cc2599255"
]
}
}}
```
```sh
curl http://localhost:1317/peggy/valset_requests -H "Content-Type: application/json"
```
* Response
Note: The result is **limited to 5 elements**
```json
{"height":"2173","result":[
{
"Nonce": "2162",
"Powers": [
"1000"
],
"EthAddresses": [
"0xb462864E395d88d6bc7C5dd5F3F5eb4cc2599255"
]
},
{
"Nonce": "6",
"Powers": [
"1000"
],
"EthAddresses": [ …
```
> Add new REST endpoints for orchestrator process

- module/x/peggy/client/rest/query.go
- module/x/peggy/client/rest/rest.go
- module/x/peggy/handler.go
- module/x/peggy/handler_test.go
- module/x/peggy/keeper/attestation_handler.go
- module/x/peggy/keeper/batch.go
- module/x/peggy/keeper/batch_test.go
- module/x/peggy/keeper/keeper.go
- module/x/peggy/keeper/oracle.go
- module/x/peggy/keeper/oracle_test.go
- module/x/peggy/keeper/pool.go
- module/x/peggy/keeper/pool_test.go
- module/x/peggy/keeper/querier.go
- module/x/peggy/types/batch.go
- module/x/peggy/types/codec.go
- module/x/peggy/types/ethereum.go
- module/x/peggy/types/expected_keepers.go
- module/x/peggy/types/key.go
- module/x/peggy/types/msgs.go
- module/x/peggy/types/oracle.go
- module/x/peggy/types/pool.go
Adds
* Attestation for bridge deposits
* Attestation for bridge withdrawals
* Attestation for bridge Multisig set updates
Rest endpoint to query last observed `nonce` by claim type.
Supported claim types:
*	BridgeDeposit
*	BridgeWithdrawalBatch
*	BridgeMultiSigUpdate
Example:
```sh
curl http://localhost:1317/peggy/last_observed_nonce/BridgeMultiSigUpdate -H "Content-Type: application/json"
```
Code not tested with a local instance. There is currently no cli support for submission of **Claims**
> Oracle attestation handles

- module/contrib/local/fake_multisig_attestation.sh
- module/x/peggy/alias.go
- module/x/peggy/client/cli/attestation_tx.go
- module/x/peggy/client/cli/query.go
- module/x/peggy/client/cli/tx.go
- module/x/peggy/client/rest/query.go
- module/x/peggy/client/rest/rest.go
- module/x/peggy/client/rest/tx.go
- module/x/peggy/handler.go
- module/x/peggy/keeper/attestation.go
- module/x/peggy/keeper/attestation_handler.go
- module/x/peggy/keeper/attestation_test.go
- module/x/peggy/keeper/batch.go
- module/x/peggy/keeper/keeper.go
- module/x/peggy/keeper/querier.go
- module/x/peggy/keeper/querier_test.go
- module/x/peggy/types/attestation.go
- module/x/peggy/types/codec.go
- module/x/peggy/types/ethereum.go
- module/x/peggy/types/events.go
- module/x/peggy/types/key.go
- module/x/peggy/types/msgs.go
- module/x/peggy/types/pool.go
Focus on Multisig Set update (valset update) confimations.
Reviewer notes:
* Batch confirmations not implemented in rest/ cli
* Current validator set is also used for threshold calculation NOT the Multisig Set
* Only minimal REST endpoints/ cli commands 
* Only minimal tests 🙈 
* Mixed `Nonce` types are still used (bytes, int64, uin64, base64 encoded bytes)
* Very early version
* Query an attestation by type:
```sh
curl http://localhost:1317/peggy/attestation/orchestrator_signed_multisig_update/459 -H "Content-Type: application/json"
curl http://localhost:1317/peggy/attestation/orchestrator_signed_multisig_update/AAAAAAAAAcs= -H "Content-Type: application/json"
```
Example response:
```json
{
"height": "1314",
"result": {
"type": "peggy/Attestation",
"value": {
"ClaimType": …
```
> Use attestations for signed executables on ETH

- module/x/peggy/keeper/attestation.go
- module/x/peggy/keeper/attestation_handler.go
- module/x/peggy/types/attestation.go
- module/x/peggy/types/msgs.go
- orchestrator/Cargo.lock
- orchestrator/cosmos_peggy/src/messages.rs
- orchestrator/cosmos_peggy/src/send.rs
- orchestrator/ethereum_peggy/src/valset_update.rs
- orchestrator/orchestrator/Cargo.toml
- orchestrator/orchestrator/src/ethereum_event_watcher.rs
- orchestrator/orchestrator/src/main.rs
- orchestrator/orchestrator/src/main_loop.rs
- orchestrator/orchestrator/src/test_runner.rs
- orchestrator/orchestrator/src/valset_relaying.rs
- orchestrator/peggy_utils/src/types.rs
- readme.md
- tests/container-scripts/integration-tests.sh
This pull request provides a working MVP of tokens going from Ethereum to Cosmos.
The actual token bridge is pretty complete in this direction as we have duplicate protection, validator voting, issuance and really everything except erc20 token hash collision handling that is required by our pre-stargate token denom length limit. 
I still need to clean up the tests and deal with some reliability edge cases around relaying events and specifically valsets in the tests.
> Ethereum to cosmos

- orchestrator/cosmos_peggy/src/lib.rs
- orchestrator/cosmos_peggy/src/send.rs
- orchestrator/cosmos_peggy/src/tests.rs
- orchestrator/orchestrator/src/client.rs
- orchestrator/orchestrator/src/test_runner.rs
There was a race condition in the tests, since we are using a validator
address to send in the validator set request sometimes the orchestrator
running at the same time and using the same key, would update the nonce
in the middle of the validator set update operation. Causing a prepetual
failure as the sequence number was never refreshed.
> Fix race condition in tests

- tests/container-scripts/integration-tests.sh
In order to deploy the contracts only once per testnet run we added
some condtional compliation to the test runner binary and ran this
version of test-runner inside of start_chains.sh. This works quite
well but presents an issue when someone attempts to run the tests
before the chain has fully finished starting.
Sicne the tests use a different version of test-runner they try and
kill the previous instance before starting. If bootstrapping is still
in progress this means that they kill the test-runner instance in
start_chains.sh and prevent the test network from ever bootstrapping
successfully.
In order to resolve this we add a simple conditional to the integration
tests that checks for the output of the bootstrapping test-runner instance
and short circuts launching further test-runner …
> Instruct the user to wait for testnet start

- module/x/peggy/keeper/attestation_handler.go
- module/x/peggy/keeper/batch.go
- module/x/peggy/keeper/batch_test.go
- module/x/peggy/types/attestation.go
- module/x/peggy/types/batch.go
- module/x/peggy/types/batch_test.go
This is to track work on finishing the transaction batch functionality
> Batch Freeing

- orchestrator/ethereum_peggy/src/send_to_cosmos.rs
- orchestrator/peggy_utils/src/types/ethereum_events.rs
Since Ethereum is BigEndian values like addreses are encoded into the
top bytes of the 32 byte uint256. This patch corrects a small defect
in the way we encoded our SendToCosmos message that placed the Cosmos
address in the least significant bytes of the message Uint256.
Because there's no validation on the Ethereum contract of the
destination Cosmos address this didn't cause any issues, but would
cause prepetual confusion for future developers writing integrations
with Peggy. Better to fix it now.
> Fix byte ordering in SendToCosmos

- module/x/peggy/keeper/querier.go
- orchestrator/orchestrator/src/test_runner.rs
- solidity/contract-deployer.ts
This patch modifies the contract deployer script to retrieve the
PeggyID from the chain parameters using a new ABCI endpoint also
included in this patch.
This allows for the chain to select a PeggyID either by placing it
into a genesis file or by voting on it as a governance paramater
after the chain starts but before the Peggy contract is deployed.
On deployment the contract deployer will retrieve the PeggyID from
the chain and the value will then be fixed in the contract storage.
At some point we should probably forbid deployments of the defualt
peggy ID in the deployment script outside of test mode. To prevent
possible failures where validators on multiple peggy chains find
signatures intended for one Peggy contract being used against another.
> Get PeggyID from blockchain params on deploy

- solidity/contracts/Peggy.sol
- solidity/test/updateValset.ts
It's an unfortunate reality of our design that many relayers will
race to submit any given batch or validator set update. Since these
are valid transactions with their own nonces and gas fees they will
be accepted by the Ethereum blockchain only to have the contract throw
shortly into their execution.
While we can't prevent this we can at least take the sting out of it.
Previously basic nonce checks where placed after checkpoint creation
meaning that with a 125 member validator set a submitter may pay $10
-$15 to hash every validiators address and then figure out with a
single integer comparison that the validator set being submitted is
the current nonce.
This patch corrects that issue by moving nonce checking as high as
possible. This should minimize gas costs for failures to only the …
> Move Peggy.sol nonce checks to the top

- orchestrator/peggy_utils/src/types/valsets.rs
- orchestrator/relayer/src/batch_relaying.rs
- orchestrator/relayer/src/valset_relaying.rs
Previously order_valset_sigs and order_batch_sigs worked by iterating
over the signatures and extracting the correct validator set members
or non-signers as seperate operations.
This is both less intutive and less correct than iterating over the
validator set members and looking up the correct signatures.
Specifically it's terribly unintutive to properly order zeroed out signatures
without iterating over the validator set members first. Since they
obviously don't exist in the signatures array and don't have an
identifier other than their power to sort.
This patch should solve the ordering problem end-to-end. Now that we
are getting the last validator set from the Ethereum event rather than
the Cosmos chain so long as we maintain the order in that event when
building our signatures array …
> Maintain sorting in order signatures

- orchestrator/test_runner/src/happy_path.rs
- tests/container-scripts/setup-validators.sh
This test just required some extra coins in the test env
to trigger the creation of more validator sets.
> Fix validator set stress test

- module/x/peggy/keeper/attestation.go
Previously the last seen event nonce for an ethereum oracle always
started at zero.
if a new validator joined the set and had never submitted
an event before they would need to play back the entire event history
in order to catch up.
From an efficiency standpoint this could involve searching over
millions of blocks and submitting thousands or tens of thousands
of oracle messages.
This patch resolves that issue starting any validator who has never
submitted an oracle event at the last observed nonce. This isn't
correct as it actually needs to be the last observed event that is
not yet past the slashing window.
> Start the eventNonce counter at last observed

- solidity/test/deployERC20.ts
This occured becuase #159 was merged without rebasing it first. This
isn't technically a conflict but it still broke things.
> Fix deployERC20 build

- module/x/peggy/abci.go
- module/x/peggy/keeper/attestation.go
- orchestrator/orchestrator/src/ethereum_event_watcher.rs
- orchestrator/test_runner/src/transaction_stress_test.rs
This fixes an consensus error created by iterating over hashmaps, as well as the test that didn't fail properly preventing us from detecting this issue before it was merged in the first place.
> Attestation endblocker fixes

- module/x/peggy/abci.go
- module/x/peggy/keeper/attestation.go
This clarifies the role of `LastObservedEventNonce` in ordering observed attestations correctly. 
I moved a check on `LastObservedEventNonce` out of some unrelated logic and into the main `attestationTally` loop. This makes it easier to understand it's role in the system. I also added some comments, like this one: 
> 
> We check if the event nonce is exactly 1 higher than LastObservedEventNonce. If it is not, we just move on to the next attestation at that nonce, and then to the next nonce. 
> 
> This loop and check logic does several different things:
> 
> - First, will skip over all attestations that have already been observed. 
> - Once it hits an event nonce that is one higher than the last observed event, it stops skipping over the conditional and starts calling TryAttestation …
> Fix unclear attestation nonce check

- module/x/peggy/keeper/msg_server.go
- orchestrator/Cargo.lock
- orchestrator/cosmos_peggy/src/send.rs
- orchestrator/ethereum_peggy/src/lib.rs
- orchestrator/ethereum_peggy/src/submit_batch.rs
- orchestrator/ethereum_peggy/src/utils.rs
- orchestrator/ethereum_peggy/src/valset_update.rs
- orchestrator/orchestrator/src/main_loop.rs
- orchestrator/relayer/src/batch_relaying.rs
- orchestrator/relayer/src/valset_relaying.rs
- orchestrator/test_runner/src/happy_path.rs
- orchestrator/test_runner/src/main.rs
- orchestrator/test_runner/src/transaction_stress_test.rs
- orchestrator/test_runner/src/utils.rs
- orchestrator/test_runner/src/valset_stress.rs
- tests/assets/ETHGenesis.json
- tests/container-scripts/integration-tests.sh
This test expands the tx stress test to live up to it's name
BATCH_STRESS and actually send batches back to Ethereum.
There are a number of challenges to this, mostly that Cosmos is very
slow about including transactions in 'block' mode although this may be
the fault of our own aggressive retry.
> Transaction scale tests should produce batches as well. 

- .github/workflows/automated-release.yml
- .gitignore
- solidity/package-lock.json
- solidity/package.json
- solidity/tsconfig.json
This patch compiles the typescript contract deployment script
into a single static binary that can be attached to the releses.
This binary includes an entire node version in order to run but in
exchange for it's heavy download weight it comes with no local
dependency requirements at all. This saves the user from needing to have
a node modules setup just to deploy the Gravity contract.
> Build contract deployment script into a static binary

- .gitignore
- module/x/peggy/client/cli/tx.go
https://github.com/althea-net/cosmos-gravity-bridge/issues/193
>  Validators need to be able to send MsgDelegateKeys from the module command line. The current Rust system will not allow validators with keys in ledgers or other HW wallets to register
> Users should be able to send MsgSendToEth and MsgSendToCosmos from the module command line. This involves submitting Ethereum transactions
I don't think sending `MsgSendToCosmos` from x/peggy module CLI makes sense. We could easily add this inside of the peggo orchestrator binary instead @xlab @jackzampolin
> add CmdSetOrchestratorAddress  and CmdSendToEth

- module/x/peggy/abci.go
- module/x/peggy/abci_test.go
- module/x/peggy/keeper/keeper.go
- module/x/peggy/keeper/keeper_test.go
- module/x/peggy/types/key.go
Changes
Advantages
- Availability of valsets for relayer to publish(to Peggy contract on L1) even after signing window.
- Stop creating valsets for each signing window.
- Reduced iterations in valset slashing logic.
> Slashing without pruning valset

- solidity/contracts/Peggy.sol
- solidity/contracts/ReentrantERC20.sol
- solidity/hardhat.config.ts
- solidity/package.json
- solidity/test/submitBatch-vs-logicCall.ts
- solidity/test/submitBatch.ts
This commit closes #221 and #190.
It reverses the order of logic contract calling and fee payment in `submitLogicCall`, and it places a reentrancy guard on `submitBatch` `submitLogicCall`, and `sendToCosmos`.
Note that I have not thought of any vulnerabilities caused by re-entrancy, and it costs a small amount of extra gas to use the guard. If we can have an auditor verify that no vulnerabilities are possible without this guard, we should remove it.
> Contract cleanup

- module/x/peggy/abci.go
This PR is to resolve
**Problem:**
If validator missed attesting both ValsetRequest and BatchRequest (due to downtime) which are created at same height  , we are trying to slash same validator twice as both slashing conditions are met.
**Solution:**
> Fix - Double jail if multiple slashing conditions are met

- orchestrator/Cargo.lock
- orchestrator/client/Cargo.toml
- orchestrator/client/src/main.rs
- orchestrator/cosmos_peggy/Cargo.toml
- orchestrator/cosmos_peggy/src/utils.rs
- orchestrator/orchestrator/Cargo.toml
- orchestrator/orchestrator/src/main.rs
- orchestrator/orchestrator/src/oracle_resync.rs
- orchestrator/peggy_utils/Cargo.toml
- orchestrator/peggy_utils/src/connection_prep.rs
- orchestrator/register_delegate_keys/Cargo.toml
- orchestrator/register_delegate_keys/src/main.rs
- orchestrator/relayer/Cargo.toml
- orchestrator/relayer/src/main.rs
- orchestrator/relayer/src/main_loop.rs
- orchestrator/test_runner/Cargo.toml
- orchestrator/test_runner/src/happy_path.rs
- orchestrator/test_runner/src/happy_path_v2.rs
- solidity/package-lock.json
This fixes some pretty glaring issues in the RPC startup parsing and
testing.
This patch also moves the code to a location where it can be called in
the integration tests.
Finally a new check was added validating that the orchestrator address
does in fact have the fee token that is being specified to spend.
> Improvements to RPC parsing and startup checks

- module/x/peggy/client/cli/tx.go
Register tx flags to the peggy subcommands send-to-eth, set-orchestrator-address, and build-batch
> module: register tx flags for peggy subcommands

- module/x/gravity/abci.go
- module/x/gravity/module.go
This patch removes the testing endblocker, which was a bad hack to try
and test the arbitrary logic integration without importing a module that
actaully uses arbitrary logic.
We still don't have a good way to test arbitrary logic end to end in
this repo and what I recomend we do in order to faciliate that is add
the ability for users to create arbitrary logic calls as part of the
core Gravity featureset.
But this patch does not do that, it just removes the ill concieved
testing endblocker.
> Remove testing endblocker

- module/x/gravity/types/types.go
- module/x/gravity/types/types_test.go
Previously this code was producing an absolute power difference, this
creates an issue where depending on the amount of active validtors and
inflation in the system the change between any two blocks may always be
greater than the 5% threshold for producing a new validator set.
This minor change normalizes the powers, the difference will always
be expressed as a percentage of uint32 max, since all powers in the
Ethereum contract always sum to that value.
> Compute normalized power difference

- orchestrator/Cargo.lock
- orchestrator/client/Cargo.toml
- orchestrator/client/src/main.rs
- orchestrator/cosmos_gravity/Cargo.toml
- orchestrator/cosmos_gravity/src/send.rs
- orchestrator/ethereum_gravity/Cargo.toml
- orchestrator/ethereum_gravity/src/utils.rs
- orchestrator/gravity_utils/Cargo.toml
- orchestrator/gravity_utils/src/connection_prep.rs
- orchestrator/gravity_utils/src/message_signatures.rs
- orchestrator/gravity_utils/src/types/batches.rs
- orchestrator/gravity_utils/src/types/ethereum_events.rs
- orchestrator/gravity_utils/src/types/logic_call.rs
- orchestrator/gravity_utils/src/types/valsets.rs
- orchestrator/orchestrator/Cargo.toml
- orchestrator/orchestrator/src/ethereum_event_watcher.rs
- orchestrator/orchestrator/src/main.rs
- orchestrator/orchestrator/src/main_loop.rs
- orchestrator/register_delegate_keys/Cargo.toml
- orchestrator/register_delegate_keys/src/main.rs
- orchestrator/relayer/Cargo.toml
- orchestrator/relayer/src/main.rs
- orchestrator/test_runner/Cargo.toml
- orchestrator/test_runner/src/happy_path.rs
- orchestrator/test_runner/src/main.rs
- orchestrator/test_runner/src/orch_keys_update.rs
- orchestrator/test_runner/src/utils.rs
This patch adds support for custom prefixes. To allow for chains with
different address prefixes than the default 'cosmos'.
Sadly this requires the user to specify the prefix as an argument when
launching the orchestrator. There's no way around this until a future
version of Cosmos exposes the prefix to clients. Looking upstream the
work for this seems to be in progress.
> Add support for custom prefixes

- orchestrator/orchestrator/src/ethereum_event_watcher.rs
Ran into a subtraction underflow error when testing using Hardhat's local network. Added support for Hardhat's default `chainId` of 31337.
> Add Hardhat chainId to block delay check

- tests/run-all-tests.sh
Disabling ARBITRARY_LOGIC test since it only runs on github actions
> Disabling the ARBITRARY_LOGIC integration test

- module/x/gravity/abci.go
- module/x/gravity/abci_test.go
- module/x/gravity/keeper/keeper_delegate_key.go
- module/x/gravity/keeper/keeper_test.go
- module/x/gravity/keeper/keeper_valset.go
- module/x/gravity/keeper/querier_test.go
Changing the valset nonces from being blockheight based to sequential by making use of the LatestValsetNonce key in keeper
> sequential valset nonces

- module/x/gravity/abci_test.go
- module/x/gravity/keeper/keeper_valset.go
- module/x/gravity/keeper/querier_test.go
LatestValsetNonce is now incremented in SetValsetRequest rather than GetCurrentValset
Closes  #279
> Moving valset nonce update outside of valset getter function

- solidity/contracts/Gravity.sol
Original title: Add nonReentrant modifier to updateValset
Original description: This is almost definitely not necessary but better safe than sorry
> Cherry-pick jtremback's non-reentrant updateValset modifier from the upstream repo

- module/x/gravity/keeper/batch.go
- module/x/gravity/keeper/batch_test.go
- module/x/gravity/keeper/genesis.go
- module/x/gravity/keeper/grpc_query.go
- module/x/gravity/keeper/pool.go
- module/x/gravity/keeper/pool_test.go
- module/x/gravity/keeper/querier.go
- module/x/gravity/types/batch.go
OutgoingTransferTx now must be converted to the InternalOutgoingTransferTx
type, which has a validated EthAddress member for destination,
InternalERC20Tokens for fee and amount
> Consistent Eth Addresses - OutgoingTransferTx

- orchestrator/relayer/src/main_loop.rs
Becuase we used 'return' instead of 'continue' here the orchestrator would unexpectedly stop if at any time during it's loops it encountered a bad response form the Ethereum node.
Since the relayer is supposed to run indefinately this is a pretty major problem. Thanks to StoykovK on the Althea discord for reporting!
> Do not exit the relayer on GravityID failure

- module/x/gravity/keeper/genesis_test.go
Good news: Bug no longer exists
Test summary: create 5000 transactions from 5 senders on 5 different contracts, batch 2500 of those into 25 batches, export the state, trash the test environment (and make sure it's trashed), init the test environment, check all the transactions still exist 
Resolves #339
> Add test for lost transactions on genesis
